# Folder preparation to use the "data_processing.py" functions

To make the functions work it is necessary that the data files supplied by Jonas need to be stored in
a separate folder "data" as a sub-folder from where your Jupyter notebooks are, then there needs to be a "sub-sub-folder" within the "data"- subfolder named "data_processed", but of course you can customize it if you want to modify the functions in "data_processing.py".

In [9]:
from data_processing import *

import warnings
warnings.filterwarnings('ignore')

Creating the Input_df for the prognosis_count function:

In [10]:
df = pd.read_csv("data/EQ_epex_da_prognosis.csv")
prognosis_count_input_df = eq_epex_da_prognosis_df_col_names(df)

The "prognosis_count(prognosis_count_input_df)"function creates a "csv" file in the "data/data_processed" folder called "EQ_epex_da_prognosis_count.csv":

In [11]:
prognosis_count(prognosis_count_input_df)

        date_prognosticated  prognosis          date_issued  prognosis_count
0       2018-12-28 00:00:00      35.95  2018-12-26 23:00:00                1
1       2018-12-28 01:00:00      34.18  2018-12-26 23:00:00                1
2       2018-12-28 02:00:00      34.00  2018-12-26 23:00:00                1
3       2018-12-28 03:00:00      34.79  2018-12-26 23:00:00                1
4       2018-12-28 04:00:00      37.88  2018-12-26 23:00:00                1
...                     ...        ...                  ...              ...
483091  2021-08-12 20:00:00      88.28  2021-07-01 22:00:00                4
483092  2021-08-12 21:00:00      78.91  2021-06-28 22:00:00                1
483093  2021-08-12 21:00:00      78.32  2021-06-29 22:00:00                2
483094  2021-08-12 21:00:00      79.96  2021-06-30 22:00:00                3
483095  2021-08-12 21:00:00      80.21  2021-07-01 22:00:00                4

[483096 rows x 4 columns]

The "current_prognosis(Input_df)" function takes an Input_df and reduces the prognoses rows to the most recent one for each timestamp. The "Input_df" is created from the "EQ_epex_da_prognosis_count.csv".

In [12]:
Input_df = pd.read_csv("data/data_processed/EQ_epex_da_prognosis_count.csv")

In [13]:
current_prognosis(Input_df)

                 timestamp  prognosis
0      2018-12-28 00:00:00      35.95
1      2018-12-28 01:00:00      34.18
2      2018-12-28 02:00:00      34.00
3      2018-12-28 03:00:00      34.79
4      2018-12-28 04:00:00      37.88
...                    ...        ...
23009  2021-08-12 17:00:00      98.67
23010  2021-08-12 18:00:00      97.19
23011  2021-08-12 19:00:00      92.55
23012  2021-08-12 20:00:00      88.28
23013  2021-08-12 21:00:00      80.21

[23014 rows x 2 columns]

The "regelleistung_df(file_path)" creates a "regelleistung_aggr_results_df" from the "regelleistung_aggr_results.csv" provided by Jonas, which is the Input Dataframe for the regelleistung_transform() function:

In [14]:
regelleistung = regelleistung_df("data/regelleistung_aggr_results.csv")
regelleistung_transform(regelleistung, "regelleistung_aggr_results3")

(674, 313) 16067
max_row_input_df:16067
max_row_output_df:673
max_col_enum_output_df:312
repeat_col_number: 13
max_repeats: 23
0 1 16067 674

,date_start,NEG_00_04MRL_total_min_capacity_price_eur_mw,NEG_00_04MRL_total_average_capacity_price_eur_mw,NEG_00_04MRL_total_marginal_capacity_price_eur_mw,NEG_00_04MRL_total_min_energy_price_eur_mwh,NEG_00_04MRL_total_average_energy_price_eur_mwh,NEG_00_04MRL_total_marginal_energy_price_eur_mwh,NEG_00_04MRL_germany_min_capacity_price_eur_mw,NEG_00_04MRL_germany_average_capacity_price_eur_mw,NEG_00_04MRL_germany_marginal_capacity_price_eur_mw,...,POS_20_24SRL_total_min_energy_price_eur_mwh,POS_20_24SRL_total_average_energy_price_eur_mwh,POS_20_24SRL_total_marginal_energy_price_eur_mwh,POS_20_24SRL_germany_min_capacity_price_eur_mw,POS_20_24SRL_germany_average_capacity_price_eur_mw,POS_20_24SRL_germany_marginal_capacity_price_eur_mw,POS_20_24SRL_germany_min_energy_price_eur_mwh,POS_20_24SRL_germany_average_energy_price_eur_mwh,POS_20_24SRL_germany_marginal_energy_price_eur_mwh,POS_20_24SRL_germany_import_export_mw
0,2019-01-01,0.0,150.81,872.262,1.0,-371.64,-18422.0,0.0,150.81,872.262,...,37.10,75.60,106.20,0.00,12.05,22.30,37.10,75.60,106.20,0.0
1,2019-01-02,0.0,130.94,292.500,5.0,-163.22,-1250.0,0.0,130.94,292.500,...,55.97,84.74,106.25,0.00,9.62,18.10,55.97,84.74,106.25,0.0
2,2019-01-03,0.0,9.60,30.026,15.0,-145.65,-600.0,0.0,9.60,30.026,...,62.00,87.53,106.25,0.00,8.13,15.48,62.00,87.53,106.25,0.0
3,2019-01-04,0.0,5.08,9.900,21.0,-37.13,-277.0,0.0,5.08,9.900,...,68.00,80.52,97.00,3.12,9.31,12.14,68.00,80.52,97.00,0.0
4,2019-01-05,0.0,4.96,17.323,18.0,-220.96,-600.0,0.0,4.96,17.323,...,64.67,80.29,101.20,2.40,8.71,13.00,64.67,80.29,101.20,0.0